title: "NFTGameAI Blog"
description: "AI-powered insights on NFT gaming, metaverse, and blockchain collectibles"
baseurl: ""
url: "https://nftgameai.com"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
