title: "NFTGameAI"
description: "AI-powered insights on NFT gaming and digital collectibles."
baseurl: ""
url: "https://nftgameai.netlify.app"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# sitemap & seo
exclude: [README.md, Gemfile, Gemfile.lock]
defaults:
  - scope:
      path: ""
    values:
      layout: default
