title: "NFTGameAI"
description: "AI-powered insights on NFT Gaming & Digital Collectibles"
baseurl: "" 
url: "https://YOUR_NETLIFY_URL_OR_DOMAIN" # đổi nếu có custom domain
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
collections: 
  posts:
    output: true

# google analytics (nếu có)
google_analytics: "G-6BDSQ4QGJN"   # đổi theo mã GA (hoặc để trống)
