#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
auto_generate.py (NFTGameAI v3)
Generate unique daily post with image, ad, backlinks, and varied AI-like content.
"""

import os, random, datetime, textwrap

DOMAINS = [
    "bottradingai.com","botgame.io","metaversebot.io","nftgameai.com","hubgaming.io",
    "botdefi.io","esportsai.io","nftgamepro.com","botesports.com","aiesports.io",
    "pronftgame.com","botplay.io","botweb3ai.com","botblockchain.io"
]

TOPICS = [
    "AI-Driven Storylines in NFT Worlds",
    "Blockchain Rewards Reshaping Game Ownership",
    "The Future of Play-to-Earn Models",
    "Metaverse Interoperability Through AI Agents",
    "Player-Owned Economies and DAO Governance",
    "How Smart Contracts Build Game Trust",
    "NFT Assets That Evolve With Gameplay",
    "Why Web3 Games Need AI Moderation",
    "Dynamic Tokenomics: Balancing Fun & Finance",
    "Virtual Marketplaces Beyond Loot Boxes"
]

TONE = [
    "In today’s fast-paced NFT ecosystem, innovation is redefining how players earn, trade, and interact.",
    "AI continues to merge with NFT gaming, creating immersive experiences and reshaping digital economies.",
    "Developers are shifting focus toward sustainable game economies, prioritizing transparency and player retention.",
    "Smart contracts now handle in-game assets seamlessly, pushing blockchain gaming closer to mass adoption.",
    "Communities in the metaverse are forming decentralized marketplaces powered by collective governance."
]

CONCLUSION = [
    "The synergy between AI, blockchain, and gaming is just beginning — and it’s already rewriting the rules of ownership.",
    "NFT gaming is evolving fast, but the projects that blend utility, creativity, and fairness will stand the test of time.",
    "As more players embrace Web3, expect gameplay that feels alive, adaptive, and driven by player decisions.",
    "Tomorrow’s top NFT games won’t just be entertainment — they’ll be entire digital economies in motion."
]

IMAGES = [
    "https://picsum.photos/1200/630?random=301",
    "https://picsum.photos/1200/630?random=302",
    "https://picsum.photos/1200/630?random=303",
    "https://picsum.photos/1200/630?random=304",
    "https://picsum.photos/1200/630?random=305",
    "https://picsum.photos/1200/630?random=306",
    "https://picsum.photos/1200/630?random=307"
]

def slugify(title):
    s = ''.join(c if c.isalnum() else '-' for c in title.lower())
    return '-'.join(filter(None, s.split('-')))

def generate_backlinks():
    links = random.sample(DOMAINS, 5)
    return "\n".join([f"- [{d}](https://{d})" for d in links])

def generate_content(title):
    intro = random.choice(TONE)
    body_parts = [
        "### Key Highlights\n",
        "- Integration of AI-driven decision systems\n"
        "- Real value through tokenized economies\n"
        "- Future potential for immersive metaverse games\n\n",
        "### Industry Insight\n",
        random.choice(TONE) + "\n",
        "### Challenges Ahead\n"
        "- Balancing speculation and gameplay depth\n"
        "- Maintaining fair reward distribution\n"
        "- Sustaining active player engagement\n\n",
        "### Expert Takeaway\n",
        random.choice(CONCLUSION)
    ]
    return "\n".join(body_parts)

def main():
    today = datetime.date.today()
    title = random.choice(TOPICS)
    slug = slugify(title)
    date_str = today.isoformat()
    filename = f"_posts/{date_str}-{slug}.md"

    content = textwrap.dedent(f"""\
    ---
    layout: post
    title: "{title}"
    date: {date_str}
    author: "NFTGameAI Team"
    description: "Daily insight: {title}"
    image: "{random.choice(IMAGES)}"
    ---

    _This post was auto-generated by NFTGameAI engine._

    ![{title}]({random.choice(IMAGES)})

    {% include ad.html %}

    {generate_content(title)}

    ### Friendly Network
    {generate_backlinks()}
    """)

    os.makedirs("_posts", exist_ok=True)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✅ Generated: {filename}")

if __name__ == "__main__":
    main()
